/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState} from "react";
import { useGLTF } from "@react-three/drei";
import { Select } from '@react-three/postprocessing'

export default function Model({ ...props }) {
    
  const [hovered, hover] = useState(null)
  const group = useRef();
  console.log(hovered);

  const { nodes, materials } = useGLTF("models/PortfolioObjects.gltf");
  return (
    <>
    <group ref={group} {...props} dispose={null} >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Table_Top.geometry}
        material={materials.Wood}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.All_Legs.geometry}
          material={materials.Wood}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SupportsL.geometry}
            material={materials.Wood}
            position={[0.29, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SupportsR.geometry}
            material={materials.Wood}
            position={[-0.48, -0.27, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Tray1L.geometry}
            material={materials.Wood}
            position={[0.33, -0.27, 0]}
          />
        </mesh>

        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Desk_Rim.geometry}
          material={materials.Wood}
          position={[0, 0.38, -0.22]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SupportBack.geometry}
          material={materials.Wood}
          position={[-0.15, -0.27, -0.21]}
          rotation={[0, 1.57, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tray2R.geometry}
          material={materials.Wood}
          position={[-0.35, -0.23, -0.08]}
          rotation={[0, -Math.PI / 4, 0]}
        />
      </mesh>

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tower.geometry}
        material={materials.Computer}
        position={[0.33, -0.04, 0]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_grate.geometry}
          material={materials["Mesh Panel"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube011.geometry}
          material={materials["Front Panels"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube011_1.geometry}
          material={materials["Mesh Panel"]}
        />
      </mesh>
      <group position={[0.3, 0.37, 0.09]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tablet_Base_1.geometry}
          material={materials["Tablet black"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tablet_Base_2.geometry}
          material={materials.pen_plastic}
        />
        <group position={[-0.14, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Knob_1.geometry}
            material={materials.pen_plastic}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Knob_2.geometry}
            material={materials.Pen_baae_plastic}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Knob_3.geometry}
            material={materials.Material}
          />
        </group>
      </group>

    <Select enabled={hovered}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pen_stand_Cylinder.geometry}
        material={materials.Pen_baae_plastic}
        position={[0.46, 0.39, -0.03]}
        onPointerOver={() => hover(true)} 
        onPointerOut={() => hover(false)}
      >
        <group position={[0.01, 0.06, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pen_Cylinder_1.geometry}
            material={materials.pen_plastic}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pen_Cylinder_2.geometry}
            material={materials.Pen_baae_plastic}
          />
        </group>
      </mesh>
    </Select>

    <Select enabled={hovered}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Big_stand_base.geometry}
        material={materials["Shiny Black Plastic"]}
        position={[0.21, 0.37, -0.13]}
        rotation={[0, -0.12, 0]}
        onPointerOver={() => hover(true)} 
        onPointerOut={() => hover(false)}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Big_stand_metal_part.geometry}
          material={materials["Big Monitor Grey Plastic"]}
          position={[0, 0.01, 0]}
        >
          <group position={[0, 0.21, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Beeg_Monitor_Screen_1.geometry}
              material={materials["Big Monitor Grey Plastic"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Beeg_Monitor_Screen_2.geometry}
              material={materials["Big Monitor Black Rim"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Beeg_Monitor_Screen_3.geometry}
              material={materials["Big Monitor Black back"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Beeg_Monitor_Screen_4.geometry}
              material={materials.Screen}
            />
          </group>
        </mesh>
      </mesh>
    </Select>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Small_stand_base.geometry}
        material={materials["Big Monitor Black back"]}
        position={[-0.31, 0.37, -0.1]}
        rotation={[0, 0.19, 0]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Monitor_holder_stem.geometry}
          material={materials["Big Monitor Black back"]}
          position={[0, 0.11, 0.03]}
        />
        <group position={[0, 0.19, 0.05]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Small_Monitor_Screen_1.geometry}
            material={materials["Big Monitor Black back"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Small_Monitor_Screen_2.geometry}
            material={materials.Screen}
          />
        </group>
      </mesh>
    </group>
    </>

  );
}

useGLTF.preload("/PortfolioObjects.gltf");